### ISSUE TITLE
NPE in PreferencesScreen

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1006]
This is pretty odd, it looks like it's throwing a NPE when trying to grab a pointer to the application.

Crash:

```
org.mozilla.mozstumbler.client.subactivities.PreferencesScreen$4.onPreferenceClick(PreferencesScreen.java:99)
```

https://github.com/mozilla/MozStumbler/blob/v0.40.1.0/android/src/main/java/org/mozilla/mozstumbler/client/subactivities/PreferencesScreen.java#L99

```
java.lang.NullPointerException
at org.mozilla.mozstumbler.client.subactivities.PreferencesScreen$4.onPreferenceClick(PreferencesScreen.java:99)
at android.preference.Preference.performClick(Preference.java:941)
at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:202)
at android.widget.AdapterView.performItemClick(AdapterView.java:292)
at android.widget.AbsListView.performItemClick(AbsListView.java:1070)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:2527)
at android.widget.AbsListView$1.run(AbsListView.java:3188)
at android.os.Handler.handleCallback(Handler.java:605)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4424)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:110)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by garvankeeley** [comment]
Crazy, getApplication() should be non-null. There must be an application to create an activity.

I think the crash is here:
https://github.com/mozilla/MozStumbler/blob/v0.40.1.0/android/src/main/java/org/mozilla/mozstumbler/client/MainApp.java#L380

That the service is not yet created.

Also, there should be a null pointer check here:
https://github.com/mozilla/MozStumbler/blob/v0.40.1.0/android/src/main/java/org/mozilla/mozstumbler/client/MainApp.java#L382

Sloppy code on my part, oops.

**Comment by garvankeeley** [comment]
pr #1007 fixes this, i hope.
