### ISSUE TITLE
LENOVO Lenovo Lenovo A316i doesn't work

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1022]
We're seeing crashes from this device running Android 4.4.4.

This error is happening deep inside of Android and looks like a firmware bug from Lenovo.

```
java.lang.NoClassDefFoundError: android.app.ANRManagerProxy
at android.app.ANRManagerNative.asInterface(ANRManagerNative.java:30)
at android.app.ANRManagerNative$1.create(ANRManagerNative.java:94)
at android.app.ANRManagerNative$1.create(ANRManagerNative.java:88)
at android.util.Singleton.get(Singleton.java:34)
at android.app.ANRManagerNative.getDefault(ANRManagerNative.java:37)
at android.os.MessageLogger.dump(MessageLogger.java:253)
at android.app.ANRAppManager.dumpMessageHistory(SourceFile:38)
at android.app.ActivityThread$ApplicationThread.dumpMessageHistory(ActivityThread.java:1176)
at android.app.ApplicationThreadNative.onTransact(ApplicationThreadNative.java:609)
at android.os.Binder.execTransact(Binder.java:351)
at dalvik.system.NativeStart.run(Native Method)
```

**Updated**: I pasted in the wrong stacktrace

**Comment by crankycoder** [comment]
I double checked against Fennec and we have similar crashes reported over there:

https://crash-stats.mozilla.com/report/index/9397696b-3727-4daf-bba5-86f9e2141017

**Comment by garvankeeley** [comment]
Is this cause by ACRA libs? I assume this is for catching 'app not-responding' os notifications.

**Comment by crankycoder** [comment]
Maybe?  But I don't think so.  Fennec wouldn't have crashstats reported.  I googled around and some Sony devices do the same thing.   

http://www.eoeandroid.com/thread-544525-1-1.html

Co-incidentally - it's also on the same 4.2.2 revision of Android.

**Comment by crankycoder** [comment]
Haven't seen this in ages in ACRA.

**Comment by seeingwithsound** [comment]
Interesting, I got the exact same crash reported only from a Lenovo A316i device with fingerprint
{Lenovo/A316i/A316i:4.2.2/JDQ39/A316i_S040_140730:user/release-keys} on Android 4.2.2 for my unrelated app The vOICe for Android, and found this report through a Google search for "NoClassDefFoundError: android.app.ANRManagerProxy" (so I did not search for Lenovo or A316i). I do not use ACRA.
