### ISSUE TITLE
MainApp::onStop crashes (if battery <15%, app crash on startup)

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1023]
Reference to the StumblerService in MainApp::onStop doesn't check for null properly.

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=org.mozilla.mozstumbler.turnMeOff flg=0x10 } in org.mozilla.mozstumbler.client.MainApp$ServiceBroadcastReceiver@41818b20
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:798)
at android.os.Handler.handleCallback(Handler.java:800)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5392)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.mozilla.mozstumbler.client.MainApp.stopScanning(MainApp.java:240)
at org.mozilla.mozstumbler.client.MainApp$ServiceBroadcastReceiver.onReceive(MainApp.java:309)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:788)
... 9 more
java.lang.NullPointerException
at org.mozilla.mozstumbler.client.MainApp.stopScanning(MainApp.java:240)
at org.mozilla.mozstumbler.client.MainApp$ServiceBroadcastReceiver.onReceive(MainApp.java:309)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:788)
at android.os.Handler.handleCallback(Handler.java:800)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5392)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by garvankeeley** [comment]
mStumblerService is tied to the lifecycle of MainApp, except there is a small (<50 ms) delay while it asynchronously creates the stumbler service. Maybe the app is receiving the low power message on startup, and receiving a stop message before mStumblerService is assigned.
