### ISSUE TITLE
Error deserializing status from JSON: org.json.JSONException: No value for status

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#1045]
I saw JSON errors like these logged every ~10 seconds. The MozStumbler app was running in the foreground, but I was not actively stumbling.

```
10-20 11:54:09.927: E/Stumbler:MLSLocationGetter(23764): Error deserializing status from JSON
10-20 11:54:09.927: E/Stumbler:MLSLocationGetter(23764): org.json.JSONException: No value for status
10-20 11:54:09.927: E/Stumbler:MLSLocationGetter(23764): at org.json.JSONObject.get(JSONObject.java:354)
10-20 11:54:09.927: E/Stumbler:MLSLocationGetter(23764): at org.json.JSONObject.getString(JSONObject.java:514)
10-20 11:54:09.927: E/Stumbler:MLSLocationGetter(23764): at org.mozilla.mozstumbler.client.mapview.MLSLocationGetter.doInBackground$44e62fb4(MLSLocationGetter.java:71)
10-20 11:54:09.927: E/Stumbler:MLSLocationGetter(23764): at org.mozilla.mozstumbler.client.mapview.MLSLocationGetter.doInBackground(MLSLocationGetter.java:26)
10-20 11:54:09.927: E/Stumbler:MLSLocationGetter(23764): at android.os.AsyncTask$2.call(AsyncTask.java:287)
10-20 11:54:09.927: E/Stumbler:MLSLocationGetter(23764): at java.util.concurrent.FutureTask.run(FutureTask.java:234)
10-20 11:54:09.927: E/Stumbler:MLSLocationGetter(23764): at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
10-20 11:54:09.927: E/Stumbler:MLSLocationGetter(23764): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
10-20 11:54:09.927: E/Stumbler:MLSLocationGetter(23764): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
10-20 11:54:09.927: E/Stumbler:MLSLocationGetter(23764): at java.lang.Thread.run(Thread.java:841)
10-20 11:54:09.927: I/ObservationPoint(23764): Error:{"timestamp":1413755514000,"wifi_count":0,"wifi":[],"lon":-122.123518,"cell_count":1,"altitude":67,"cell":[{"asu":14,"radio":"0","mnc":260,"psc":0,"mcc":310}],"radio":"gsm","accuracy":11,"lat":37.956794}

10-20 11:54:11.188: D/Stumbler:HTTPResponse(23764): HTTP Status: 400, Bytes Sent: 165, Bytes received: 106
10-20 11:54:11.198: E/Stumbler:MLSLocationGetter(23764): Error deserializing status from JSON
10-20 11:54:11.198: E/Stumbler:MLSLocationGetter(23764): org.json.JSONException: No value for status
10-20 11:54:11.198: E/Stumbler:MLSLocationGetter(23764): at org.json.JSONObject.get(JSONObject.java:354)
10-20 11:54:11.198: E/Stumbler:MLSLocationGetter(23764): at org.json.JSONObject.getString(JSONObject.java:514)
10-20 11:54:11.198: E/Stumbler:MLSLocationGetter(23764): at org.mozilla.mozstumbler.client.mapview.MLSLocationGetter.doInBackground$44e62fb4(MLSLocationGetter.java:71)
10-20 11:54:11.198: E/Stumbler:MLSLocationGetter(23764): at org.mozilla.mozstumbler.client.mapview.MLSLocationGetter.doInBackground(MLSLocationGetter.java:26)
10-20 11:54:11.198: E/Stumbler:MLSLocationGetter(23764): at android.os.AsyncTask$2.call(AsyncTask.java:287)
10-20 11:54:11.198: E/Stumbler:MLSLocationGetter(23764): at java.util.concurrent.FutureTask.run(FutureTask.java:234)
10-20 11:54:11.198: E/Stumbler:MLSLocationGetter(23764): at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
10-20 11:54:11.198: E/Stumbler:MLSLocationGetter(23764): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
10-20 11:54:11.198: E/Stumbler:MLSLocationGetter(23764): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
10-20 11:54:11.198: E/Stumbler:MLSLocationGetter(23764): at java.lang.Thread.run(Thread.java:841)
10-20 11:54:11.198: I/ObservationPoint(23764): Error:{"timestamp":1413755486000,"wifi_count":0,"wifi":[],"lon":-122.123379,"cell_count":1,"altitude":60,"cell":[{"asu":14,"radio":"0","mnc":260,"psc":0,"mcc":310}],"radio":"gsm","accuracy":14,"lat":37.957195}

10-20 11:54:12.420: D/Stumbler:HTTPResponse(23764): HTTP Status: 400, Bytes Sent: 167, Bytes received: 106
10-20 11:54:12.420: E/Stumbler:MLSLocationGetter(23764): Error deserializing status from JSON
10-20 11:54:12.420: E/Stumbler:MLSLocationGetter(23764): org.json.JSONException: No value for status
10-20 11:54:12.420: E/Stumbler:MLSLocationGetter(23764): at org.json.JSONObject.get(JSONObject.java:354)
10-20 11:54:12.420: E/Stumbler:MLSLocationGetter(23764): at org.json.JSONObject.getString(JSONObject.java:514)
10-20 11:54:12.420: E/Stumbler:MLSLocationGetter(23764): at org.mozilla.mozstumbler.client.mapview.MLSLocationGetter.doInBackground$44e62fb4(MLSLocationGetter.java:71)
10-20 11:54:12.420: E/Stumbler:MLSLocationGetter(23764): at org.mozilla.mozstumbler.client.mapview.MLSLocationGetter.doInBackground(MLSLocationGetter.java:26)
10-20 11:54:12.420: E/Stumbler:MLSLocationGetter(23764): at android.os.AsyncTask$2.call(AsyncTask.java:287)
10-20 11:54:12.420: E/Stumbler:MLSLocationGetter(23764): at java.util.concurrent.FutureTask.run(FutureTask.java:234)
10-20 11:54:12.420: E/Stumbler:MLSLocationGetter(23764): at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
10-20 11:54:12.420: E/Stumbler:MLSLocationGetter(23764): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
10-20 11:54:12.420: E/Stumbler:MLSLocationGetter(23764): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
10-20 11:54:12.420: E/Stumbler:MLSLocationGetter(23764): at java.lang.Thread.run(Thread.java:841)
10-20 11:54:12.430: I/ObservationPoint(23764): Error:{"timestamp":1413755514000,"wifi_count":0,"wifi":[],"lon":-122.123518,"cell_count":1,"altitude":67,"cell":[{"asu":14,"radio":"0","mnc":260,"psc":0,"mcc":310}],"radio":"gsm","accuracy":11,"lat":37.956794}
```

**Comment by garvankeeley** [comment]
This code got changed at some point and is missing an http status check, will fix
