### ISSUE TITLE
Crash when no telephony type is available. 

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1137]
```
java.lang.UnsupportedOperationException: Unexpected Phone Type: 0
at org.mozilla.mozstumbler.service.stumblerthread.scanners.cellscanner.CellScannerImplementation.start(CellScannerImplementation.java:92)
at org.mozilla.mozstumbler.service.stumblerthread.scanners.cellscanner.CellScanner.start(CellScanner.java:77)
at org.mozilla.mozstumbler.service.stumblerthread.scanners.ScanManager.startScanning(ScanManager.java:114)
at org.mozilla.mozstumbler.service.stumblerthread.StumblerService.startScanning(StumblerService.java:63)
at org.mozilla.mozstumbler.client.MainApp.startScanning(MainApp.java:234)
at org.mozilla.mozstumbler.client.navdrawer.MainDrawerActivity$3.run(MainDrawerActivity.java:207)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by garvankeeley** [comment]
Make logging quieter on fennec. Re-opening and self-assigning, as a Fennec to-do item
