### ISSUE TITLE
ACRA Report: NPE WifiScanner.java:44 (and 46 in 1020000)

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1187]
Caused by: java.lang.NullPointerException
at android.content.ContextWrapper.getApplicationContext(ContextWrapper.java:109)
at org.mozilla.mozstumbler.service.stumblerthread.scanners.WifiScanner.<init>(WifiScanner.java:44)
at org.mozilla.mozstumbler.service.stumblerthread.Reporter.<init>(Reporter.java:52)
at org.mozilla.mozstumbler.service.stumblerthread.StumblerService.<init>(StumblerService.java:56)
at org.mozilla.mozstumbler.service.stumblerthread.StumblerService.<init>(StumblerService.java:51)
at org.mozilla.mozstumbler.client.ClientStumblerService.<init>(ClientStumblerService.java:21)

**Comment by garvankeeley** [comment]
Here is for 1020000:
Caused by: java.lang.NullPointerException
at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:467)
at org.mozilla.mozstumbler.service.stumblerthread.scanners.WifiScanner.<init>(WifiScanner.java:46)
at org.mozilla.mozstumbler.service.stumblerthread.Reporter.<init>(Reporter.java:52)
at org.mozilla.mozstumbler.service.stumblerthread.StumblerService.<init>(StumblerService.java:56)
at org.mozilla.mozstumbler.service.stumblerthread.StumblerService.<init>(StumblerService.java:51)
at org.mozilla.mozstumbler.client.ClientStumblerService.<init>(ClientStumblerService.java:21)
