### ISSUE TITLE
ACRA Report: NPE StumblerService.<init>(StumblerService.java:37)

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1188]
java.lang.NullPointerException
at org.mozilla.mozstumbler.service.stumblerthread.scanners.ScanManager.<init>(ScanManager.java:35)
at org.mozilla.mozstumbler.service.stumblerthread.StumblerService.<init>(StumblerService.java:37)
at org.mozilla.mozstumbler.service.stumblerthread.StumblerService.<init>(StumblerService.java:51)
at org.mozilla.mozstumbler.client.ClientStumblerService.<init>(ClientStumblerService.java:21)

**Comment by garvankeeley** [comment]
This doesn't line up with anything in the code that I can see. May close for now and see if gets reproduced.

**Comment by cascheberg** [comment]
Is it possible that crashes of builds that have been modified and built locally are also uploaded?  (Maybe due to 204d81c417f0653206aac7f738ebff37bad8ba97, @crankycoder is that push supposed to include an API key and ACRA password?)

**Comment by crankycoder** [comment]
Good point.  This might be local builds throwing errors. I should modify
the build to include the git revision and build host in the version name.

Yes,  the acra configuration is meant to be in there. This is mostly for
fdroid.

**Comment by garvankeeley** [comment]
I'll close this, as it isn't actionable, and I think the other NPE fixes we put in caught this.
