### ISSUE TITLE
ACRA: NPE BatteryCheck.batteryLevel

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1293]
java.lang.SecurityException: Unable to find app for caller android.app.ApplicationThreadProxy@436130e8 (pid=12014) when registering receiver null
at android.os.Parcel.readException(Parcel.java:1465)
at android.os.Parcel.readException(Parcel.java:1419)
at android.app.ActivityManagerProxy.registerReceiver(ActivityManagerNative.java:2330)
at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1450)
at android.app.ContextImpl.registerReceiver(ContextImpl.java:1418)
at android.app.ContextImpl.registerReceiver(ContextImpl.java:1412)
at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:467)
at org.mozilla.mozstumbler.service.utils.BatteryCheck.batteryLevel(BatteryCheck.java:16)
at org.mozilla.mozstumbler.service.utils.BatteryCheck.isBatteryLessThan(BatteryCheck.java:32)
at org.mozilla.mozstumbler.client.ClientStumblerService$1.run(ClientStumblerService.java:96)

**Comment by garvankeeley** [comment]
No longer relevant
