### ISSUE TITLE
1.7.1 crash in MotionSensor 

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1515]
This is a bit confusing.  I would say that mContext should use an application context, but tracing back the call stack shows that start(Context) uses an application context already.

``` java
        public void start(Context c) {
            mContext = c;
            LocationManager lm = (LocationManager) mContext.getSystemService(Context.LOCATION_SERVICE);

            if (mLastLocation == null) {
                mLastLocation = lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);
                if (mLastLocation == null) {
                    mLastLocation = lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);
                }
            }

            lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER, 0, 0, mNetworkLocationListener);
        }
```

Crash log:

``` java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
at org.mozilla.mozstumbler.service.stumblerthread.motiondetection.MotionSensor$NetworkLocationChangeDetector.stop(MotionSensor.java:176)
at org.mozilla.mozstumbler.service.stumblerthread.motiondetection.MotionSensor.stop(MotionSensor.java:134)
at org.mozilla.mozstumbler.service.stumblerthread.scanners.ScanManager.stopAllScanners(ScanManager.java:239)
at org.mozilla.mozstumbler.service.stumblerthread.scanners.ScanManager.stopScanning(ScanManager.java:226)
at org.mozilla.mozstumbler.client.ClientStumblerService.stopScanning(ClientStumblerService.java:73)
at org.mozilla.mozstumbler.client.MainApp.stopScanning(MainApp.java:289)
at org.mozilla.mozstumbler.client.mapview.MapFragment.toggleScanning(MapFragment.java:481)
at org.mozilla.mozstumbler.client.navdrawer.MainDrawerActivity$1.onCheckedChanged(MainDrawerActivity.java:56)
at android.widget.CompoundButton.setChecked(CompoundButton.java:152)
at android.widget.Switch.setChecked(Switch.java:852)
at android.widget.Switch.toggle(Switch.java:847)
at android.widget.CompoundButton.performClick(CompoundButton.java:124)
at android.view.View$PerformClick.run(View.java:19749)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by crankycoder** [comment]
Not sure if it helps, but I see this happening a lot on Nexus 4, running Android 5.0.1
