### ISSUE TITLE
ConcurrentModification error in v1.6.1

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1520]
```
Caused by: java.util.ConcurrentModificationException
at java.util.LinkedList$LinkIterator.next(LinkedList.java)
at org.mozilla.mozstumbler.client.serialize.ObservationPointSerializer.writeOut(ObservationPointSerializer.java:130)
at org.mozilla.mozstumbler.client.serialize.ObservationPointSerializer.doInBackground(ObservationPointSerializer.java:309)
at org.mozilla.mozstumbler.client.serialize.ObservationPointSerializer.doInBackground(ObservationPointSerializer.java:43)
at android.os.AsyncTask$2.call(AsyncTask.java)
```

**Comment by crankycoder** [comment]
Fixed in #1522
