### ISSUE TITLE
new async uploader FileNotFoundException causing crash (not in release)

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#1679]
I think we need to double check if the storage directory somehow got wiped out.    If the directory is not there, we should try to recreate it.  

If that fails, we should immediately terminate the application.

On application startup, if the storage directory can't be created - there should be some kind of meaningful notification to the user that no reports can be saved or loaded from Android storage.

We see this crash show up dozens of times from individual devices - so this is a pretty high priority.

Crash report from 1.7.12 :

```
STACK_TRACE 
0   java.io.FileNotFoundException: /data/data/org.mozilla.mozstumbler/files/reports/report-t1434113604197-r0-w0-c0.gz: open failed: ENOENT (No such file or directory)
1   at libcore.io.IoBridge.open(IoBridge.java:456)
2   at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
3   at org.mozilla.mozstumbler.service.stumblerthread.datahandling.base.SerializedJSONRowsList$Iterator.readFile(SerializedJSONRowsList.java:44)
4   at org.mozilla.mozstumbler.service.stumblerthread.datahandling.base.SerializedJSONRowsList$Iterator.getAtCurrentIndex(SerializedJSONRowsList.java:27)
5   at org.mozilla.mozstumbler.service.stumblerthread.datahandling.base.JSONRowsStorageManager.getNextBatch(JSONRowsStorageManager.java:139)
6   at org.mozilla.mozstumbler.service.uploadthread.AsyncUploader.uploadReports(AsyncUploader.java:165)
7   at org.mozilla.mozstumbler.service.uploadthread.AsyncUploader.doInBackground(AsyncUploader.java:81)
8   at org.mozilla.mozstumbler.service.uploadthread.AsyncUploader.doInBackground(AsyncUploader.java:43)
9   at android.os.AsyncTask$2.call(AsyncTask.java:292)
10  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
12  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
13  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
14  at java.lang.Thread.run(Thread.java:818)
15  Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
16  at libcore.io.Posix.open(Native Method)
17  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
18  at libcore.io.IoBridge.open(IoBridge.java:442)
19  ... 13 more
20  android.system.ErrnoException: open failed: ENOENT (No such file or directory)
21  at libcore.io.Posix.open(Native Method)
22  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
23  at libcore.io.IoBridge.open(IoBridge.java:442)
24  at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
25  at org.mozilla.mozstumbler.service.stumblerthread.datahandling.base.SerializedJSONRowsList$Iterator.readFile(SerializedJSONRowsList.java:44)
26  at org.mozilla.mozstumbler.service.stumblerthread.datahandling.base.SerializedJSONRowsList$Iterator.getAtCurrentIndex(SerializedJSONRowsList.java:27)
27  at org.mozilla.mozstumbler.service.stumblerthread.datahandling.base.JSONRowsStorageManager.getNextBatch(JSONRowsStorageManager.java:139)
28  at org.mozilla.mozstumbler.service.uploadthread.AsyncUploader.uploadReports(AsyncUploader.java:165)
29  at org.mozilla.mozstumbler.service.uploadthread.AsyncUploader.doInBackground(AsyncUploader.java:81)
30  at org.mozilla.mozstumbler.service.uploadthread.AsyncUploader.doInBackground(AsyncUploader.java:43)
31  at android.os.AsyncTask$2.call(AsyncTask.java:292)
32  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
33  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
34  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
35  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
36  at java.lang.Thread.run(Thread.java:818)
37  
```

**Comment by garvankeeley** [comment]
We do create the storage dir on request.

**Comment by garvankeeley** [comment]
This stack trace is scary. We have the upload task being called twice, and racing to access the file, which then disappears unexpectedly.

**Comment by garvankeeley** [comment]
This is new code, not in release yet. Thankfully.

**Comment by garvankeeley** [comment]
Oops, it only looked nested from the way this report was, fixing the name of this bug.

**Comment by garvankeeley** [comment]
JSONRowsStorageManager.mFileList is not in-sync with the actual state on disk.
mFileList.update() is what needs to be called to do this.

One obvious place it is missing is in the finally block of: https://github.com/mozilla/MozStumbler/blob/cdffa69a847324fcfdea497a28819c64746627a8/libraries/stumbler/src/main/java/org/mozilla/mozstumbler/service/stumblerthread/datahandling/base/JSONRowsStorageManager.java#L223
But that is a very rare case that would get hit.

**Comment by garvankeeley** [comment]
Are all the crash reports files named r0-w0-c0?

**Comment by garvankeeley** [comment]
Sigh, nevermind. Fixing my broken code...
