### ISSUE TITLE
Metrics view updated from wrong thread (ACRA crash)

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#1680]
```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7081)
at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1107)
at android.view.ViewGroup.invalidateChild(ViewGroup.java:4529)
at android.view.View.invalidate(View.java:11809)
at android.view.View.invalidate(View.java:11750)
at android.widget.TextView.checkForRelayout(TextView.java:8047)
at android.widget.TextView.setText(TextView.java:4866)
at android.widget.TextView.setText(TextView.java:4719)
at android.widget.TextView.setText(TextView.java:4694)
at org.mozilla.mozstumbler.client.navdrawer.MetricsView.updateSentStats(MetricsView.java:291)
at org.mozilla.mozstumbler.client.navdrawer.MetricsView.access$100(MetricsView.java:45)
at org.mozilla.mozstumbler.client.navdrawer.MetricsView$1.onReceive(MetricsView.java:81)
at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
at android.support.v4.content.LocalBroadcastManager.sendBroadcastSync(LocalBroadcastManager.java:278)
at org.mozilla.mozstumbler.service.stumblerthread.scanners.ScanManager$4.run(ScanManager.java:180)
at java.util.Timer$TimerImpl.run(Timer.java:284)
```

**Comment by crankycoder** [comment]
Duplicate of #1672

**Comment by garvankeeley** [comment]
non dup, will add a guard for this now
