### ISSUE TITLE
Mozilla Stumbler occasionally crashes while collecting data

### ISSUE THREAD

**Issue by Iey4iej3** [mozilla/MozStumbler#1805]
Build: Mozilla Stumbler 1.8.6, 7aaf00b-dirty, installed from F-Droid.

I don't know what exactly leads Mozilla Stumbler to a crash. I started it to collect data, then walked along the street. When I came home, I found that Mozilla Stumbler was off. I read the logcat, and found:

10-15 19:24:15.090 19228  5468 E AndroidRuntime: FATAL EXCEPTION: Thread-6069
10-15 19:24:15.090 19228  5468 E AndroidRuntime: Process: org.mozilla.mozstumbler, PID: 19228
10-15 19:24:15.090 19228  5468 E AndroidRuntime: Theme: themes:{}
10-15 19:24:15.090 19228  5468 E AndroidRuntime: java.lang.InternalError: Thread starting during runtime shutdown
10-15 19:24:15.090 19228  5468 E AndroidRuntime:    at java.lang.Thread.nativeCreate(Native Method)
10-15 19:24:15.090 19228  5468 E AndroidRuntime:    at java.lang.Thread.start(Thread.java:1063)
10-15 19:24:15.090 19228  5468 E AndroidRuntime:    at org.apache.http.impl.conn.tsccm.AbstractConnPool.enableConnectionGC(AbstractConnPool.java:145)
10-15 19:24:15.090 19228  5468 E AndroidRuntime:    at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.createConnectionPool(ThreadSafeClientConnManager.java:125)
10-15 19:24:15.090 19228  5468 E AndroidRuntime:    at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager.<init>(ThreadSafeClientConnManager.java:103)
10-15 19:24:15.090 19228  5468 E AndroidRuntime:    at org.acra.util.HttpRequest.getHttpClient(HttpRequest.java:214)
10-15 19:24:15.090 19228  5468 E AndroidRuntime:    at org.acra.util.HttpRequest.send(HttpRequest.java:141)
10-15 19:24:15.090 19228  5468 E AndroidRuntime:    at org.acra.sender.HttpSender.send(HttpSender.java:225)
10-15 19:24:15.090 19228  5468 E AndroidRuntime:    at org.acra.SendWorker.sendCrashReport(SendWorker.java:179)
10-15 19:24:15.090 19228  5468 E AndroidRuntime:    at org.acra.SendWorker.checkAndSendReports(SendWorker.java:141)
10-15 19:24:15.090 19228  5468 E AndroidRuntime:    at org.acra.SendWorker.run(SendWorker.java:77)
10-15 19:24:15.109  2540  3436 I chatty  : uid=1000(system) Binder_A expire 1 line
10-15 19:24:15.116  2540  2580 I chatty  : uid=1000(system) ActivityManager expire 1 line
10-15 19:24:15.175  2540  2680 D WifiService: Client connection lost with reason: 4
10-15 19:24:15.202  2540  2796 I ActivityManager: Process org.mozilla.mozstumbler (pid 19228) has died

**Comment by Iey4iej3** [comment]
Another log was caught yesterday.
[moz.txt](https://github.com/mozilla/MozStumbler/files/628775/moz.txt)
