### ISSUE TITLE
Crash really often

### ISSUE THREAD

**Issue by jeremy447** [mozilla/MozStumbler#1820]
Hello,

MozStumbler crash really often on my Razr i (x86 - no google services)

Here is a log : 
[2017-06-25-14-44-56.txt](https://github.com/mozilla/MozStumbler/files/1104158/2017-06-25-14-44-56.txt)

MozStumbler version: 1.8.6
Android version: 4.4

Thanks !

**Comment by jeremy447** [comment]
I really hope that bug can be fixed because I really want to contribute but it's not possible with that issue.

**Comment by garvankeeley** [comment]
First it looks like stumbler is killed, perhaps due to low memory:
```
06-25 14:44:40.501 I/DEBUG   (166): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-25 14:44:40.501 I/DEBUG   (166): Build fingerprint: 'Motorola/lineage_smi/smi:4.4.4/KTU84Q/364774f6cc:userdebug/test-keys'
06-25 14:44:40.501 I/DEBUG   (166): Revision: '0'
06-25 14:44:40.501 I/DEBUG   (166): pid: 11129, tid: 11133, name: GC  >>> org.mozilla.mozstumbler <<<
06-25 14:44:40.501 I/DEBUG   (166): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000025
06-25 14:44:40.611 D/dalvikvm(11038): GC_CONCURRENT freed 1388K, 37% free 8605K/13628K, paused 1ms+21ms, total 67ms
06-25 14:44:40.611 D/dalvikvm(11038): WAIT_FOR_CONCURRENT_GC blocked 30ms
06-25 14:44:40.621 D/dalvikvm(11038): WAIT_FOR_CONCURRENT_GC blocked 31ms
06-25 14:44:41.001 I/ActivityManager(524): Process org.geometerplus.zlibrary.ui.android:synchroniser (pid 6515) has died.
06-25 14:44:41.001 D/ActivityManager(524): cleanUpApplicationRecordLocked -- 6515
06-25 14:44:41.011 W/ActivityManager(524): Scheduling restart of crashed service org.geometerplus.zlibrary.ui.android/org.geometerplus.android.fbreader.sync.SyncService in 1000ms
06-25 14:44:41.031 D/IchnaeaBackendService(9566): Cells: 4
06-25 14:44:41.041 I/DEBUG   (166):     eax 00000002  ebx 0ae00100  ecx 42946a10  edx 00000002
06-25 14:44:41.041 I/DEBUG   (166):     esi 00000004  edi 430c1fec
06-25 14:44:41.041 I/DEBUG   (166):     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
06-25 14:44:41.041 I/DEBUG   (166):     eip 42946a43  ebp 565d5b98  esp 565d5b50  flags 00210293
06-25 14:44:41.041 I/DEBUG   (166): 
06-25 14:44:41.041 I/DEBUG   (166): backtrace:
06-25 14:44:41.041 I/DEBUG   (166):     #00  pc 000a6a43  /system/lib/libdvm.so (scanBitmapCallback(Object*, void*, void*)+51)
06-25 14:44:41.041 I/DEBUG   (166):     #01  pc 00092399  /system/lib/libdvm.so (dvmHeapBitmapScanWalk(HeapBitmap*, unsigned int, unsigned int, void (*)(Object*, void*, void*), void*)+137)
06-25 14:44:41.041 I/DEBUG   (166):     #02  pc 000a81c3  /system/lib/libdvm.so (dvmHeapScanMarkedObjects(bool)+67)
06-25 14:44:41.041 I/DEBUG   (166):     #03  pc 000931b6  /system/lib/libdvm.so (dvmCollectGarbageInternal(GcSpec const*)+2198)
06-25 14:44:41.041 I/DEBUG   (166):     #04  pc 00149e4f  /system/lib/libdvm.so (gcDaemonThread(void*)+447)
06-25 14:44:41.041 I/DEBUG   (166):     #05  pc 000f3b3b  /system/lib/libdvm.so (internalThreadStart(void*)+523)
06-25 14:44:41.041 I/DEBUG   (166):     #06  pc 0001b9cb  /system/lib/libc.so (__thread_entry+219)
06-25 14:44:41.041 I/DEBUG   (166):     #07  pc 00049df5  /system/lib/libc.so (__pthread_clone+69)
06-25 14:44:41.041 I/DEBUG   (166):     #08  pc 000f392f  /system/lib/libdvm.so
06-25 14:44:41.041 I/DEBUG   (166):     #09  pc 000fcfff  <unknown>
06-25 14:44:41.041 I/DEBUG   (166):     #10  pc 00000000  <unknown>

```

Later I see this in the log:
```
06-25 14:44:41.841 W/ActivityManager(524):   Force finishing activity org.mozilla.mozstumbler/.client.navdrawer.MainDrawerActivity
06-25 14:44:41.871 E/JavaBinder(524): !!! FAILED BINDER TRANSACTION !!!
06-25 14:44:41.871 W/InputDispatcher(524): channel '2229a21c org.mozilla.mozstumbler/org.mozilla.mozstumbler.client.navdrawer.MainDrawerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-25 14:44:41.871 E/InputDispatcher(524): channel '2229a21c org.mozilla.mozstumbler/org.mozilla.mozstumbler.client.navdrawer.MainDrawerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-25 14:44:41.871 W/InputDispatcher(524): Attempted to unregister already unregistered input channel '2229a21c org.mozilla.mozstumbler/org.mozilla.mozstumbler.client.navdrawer.MainDrawerActivity (server)'
06-25 14:44:41.871 W/ActivityManager(524): Exception thrown during pause
06-25 14:44:41.871 W/ActivityManager(524): android.os.TransactionTooLargeException
06-25 14:44:41.871 W/ActivityManager(524): 	at android.os.BinderProxy.transact(Native Method)
06-25 14:44:41.871 W/ActivityManager(524): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
06-25 14:44:41.871 W/ActivityManager(524): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:766)
06-25 14:44:41.871 W/ActivityManager(524): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2500)
06-25 14:44:41.871 W/ActivityManager(524): 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2377)
06-25 14:44:41.871 W/ActivityManager(524): 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2068)
06-25 14:44:41.871 W/ActivityManager(524): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9766)
06-25 14:44:41.871 W/ActivityManager(524): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9659)
06-25 14:44:41.871 W/ActivityManager(524): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10310)
06-25 14:44:41.871 W/ActivityManager(524): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9855)
06-25 14:44:41.871 W/ActivityManager(524): 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
06-25 14:44:41.871 I/WindowState(524): WIN DEATH: Window{2229a21c u0 org.mozilla.mozstumbler/org.mozilla.mozstumbler.client.navdrawer.MainDrawerActivity}
06-25 14:44:41.881 I/ActivityManager(524): Process org.mozilla.mozstumbler (pid 11129) has died.
```

**Comment by garvankeeley** [comment]
The 'binder' errors may indicate too much data being sent between processes (perhaps the Intent bundle is too large and should be bounded)

**Comment by txjockey** [comment]
Im seeing a lot of crashes too (along with points not updating)

**Comment by JonnyTech** [comment]
Are you using microG instead of Google services? I noticed a similar problem and had to switch location services to device only rather than network assisted (effectively disabling NLP's). Unfortunately nothing shows up in my log. If you can confirm that then I shall raise an issue with microG.
