### ISSUE TITLE
Crash Report submission fails due to expired cert at mozstumbler-crashes.stage.mozaws.net

### ISSUE THREAD

**Issue by dholbert** [mozilla/MozStumbler#1857]
I've been hitting some crashes in MozStumbler using Android Q beta on my Pixel 3 (and I'll file those crashes separately), and I noticed this logging in my adb logcat output:
```
Sending request to https://mozstumbler-crashes.stage.mozaws.net/acra-stumbler/_design/acra-storage/_update/report/ede339fe-1e3a-4cea-a1bf-4706dcbbfda0
Failed to send crash report for 1553276225000-approved.stacktrace
org.acra.sender.ReportSenderException: Error while sending JSON report via Http PUT
     at org.acra.sender.HttpSender.send(HttpSender.java:228)
     at org.acra.SendWorker.sendCrashReport(SendWorker.java:179)
     at org.acra.SendWorker.checkAndSendReports(SendWorker.java:141)
     at org.acra.SendWorker.run(SendWorker.java:77)
Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
[...]
Caused by: java.security.cert.CertificateException: Chain validation failed
[...]
Caused by: java.security.cert.CertPathValidatorException: timestamp check failed
     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
[...]
Caused by: java.security.cert.CertificateExpiredException: Certificate expired at Wed Apr 12 05:00:00 PDT 2017 (compared to Fri Mar 22 10:39:51 PDT 2019)
```

Indeed, https://mozstumbler-crashes.stage.mozaws.net seems to have an expired cert (which you can see if you directly visit it in a browser). I suspect that means we've been unable to receive crash reports since April of 2017 (when the cert expired).

**Comment by dholbert** [comment]
Oh, I guess this was previously filed as #1827.
