### ISSUE TITLE
Error uploading observations

### ISSUE THREAD

**Issue by rodmoreno** [mozilla/MozStumbler#511]
I have a cell with Firefox OS a Geeksphone Keon and I decided putting on a ROM with Android (http://sys.nodo21.org/geeksphone-keon-rom) to make scans with a second mobile operator and thus contribute more to this great project .

But my surprise was that never uploaded any report (the good thing is to scan a small area) and then decided to find out more, use the logcat and threw me the following:

```
03-20 08:20:23.861    1298-2064/org.mozilla.mozstumbler:.ScannerService E/org.mozilla.mozstumbler.communicator.Submitter﹕ Error submitting:
    org.mozilla.mozstumbler.communicator.AbstractCommunicator$HttpErrorException
            at org.mozilla.mozstumbler.communicator.AbstractCommunicator.sendData(AbstractCommunicator.java:96)
            at org.mozilla.mozstumbler.communicator.AbstractCommunicator.send(AbstractCommunicator.java:109)
            at org.mozilla.mozstumbler.communicator.Submitter.cleanSend(Submitter.java:40)
            at org.mozilla.mozstumbler.sync.SyncAdapter.onPerformSync(SyncAdapter.java:91)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)
```

I could also see the following error repeated several times:

`03-20 08:19:39.959    1298-2054/org.mozilla.mozstumbler:.ScannerService E/org.mozilla.mozstumbler.cellscanner.CellInfo﹕ java.lang.IllegalArgumentException: Unexpected network type: 0
            at org.mozilla.mozstumbler.cellscanner.CellInfo.getCellRadioTypeName(CellInfo.java:320)
            at org.mozilla.mozstumbler.cellscanner.CellInfo.setCellLocation(CellInfo.java:176)
            at org.mozilla.mozstumbler.cellscanner.DefaultCellScanner.getCurrentCellInfo(DefaultCellScanner.java:125)
            at org.mozilla.mozstumbler.cellscanner.DefaultCellScanner.getCellInfo(DefaultCellScanner.java:91)
            at org.mozilla.mozstumbler.cellscanner.CellScanner$1.run(CellScanner.java:64)
            at java.util.Timer$TimerImpl.run(Timer.java:284)`

Believe it very critical?

**Comment by Djfe** [comment]
Is the ROM just emulated?
At least it looks like your Rom doesn't support the Android Sync Adapter and serves wrong network types (0)

**Comment by Djfe** [comment]
You could use Firefox OS and FXStumbler instead ;)

**Comment by rodmoreno** [comment]
@Djfe No is a full ROM, is rare because in fact if properly supports synchronization, capture here as in the case of MozStumbler not want to sync with Google sync but perfect:
![media-20140320](https://f.cloud.github.com/assets/4095436/2475031/a8bdbdbc-b052-11e3-8ce5-43b4089a31cc.png)
And I have not found way how to enable synchronization

**Comment by tamcap** [comment]
Ichnaea for some reason does not want to accept your data, and gives us a non-OK response code. Hence the error code. The wrong cell network id might or might not be related to it...

**Comment by Djfe** [comment]
Does mozstumbler recognize cells in your phone?

**Comment by tamcap** [comment]
If you would like to debug it deeper, try running this experimental release and show us what Log.d prints when the error occurs:

https://github.com/tamcap/MozStumbler/releases/tag/v0.16.0.debug

**Comment by rodmoreno** [comment]
@Djfe Yes, of course!

@tamcap already installed the experimental version and when I got the error showed me the following:

```
03-22 08:20:15.110    3542-3798/org.mozilla.mozstumbler:.ScannerService E/org.mozilla.mozstumbler.communicator.AbstractCommunicator﹕ Couldn't compress and send data, falling back to plain-text:
    org.mozilla.mozstumbler.communicator.AbstractCommunicator$HttpErrorException
            at org.mozilla.mozstumbler.communicator.AbstractCommunicator.sendData(AbstractCommunicator.java:96)
            at org.mozilla.mozstumbler.communicator.AbstractCommunicator.send(AbstractCommunicator.java:104)
            at org.mozilla.mozstumbler.communicator.Submitter.cleanSend(Submitter.java:41)
            at org.mozilla.mozstumbler.sync.SyncAdapter.uploadReports(SyncAdapter.java:130)
            at org.mozilla.mozstumbler.sync.SyncAdapter.onPerformSync(SyncAdapter.java:91)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)
03-22 08:20:15.831    3542-3798/org.mozilla.mozstumbler:.ScannerService E/org.mozilla.mozstumbler.communicator.Submitter﹕ Error submitting:
    org.mozilla.mozstumbler.communicator.AbstractCommunicator$HttpErrorException
            at org.mozilla.mozstumbler.communicator.AbstractCommunicator.sendData(AbstractCommunicator.java:96)
            at org.mozilla.mozstumbler.communicator.AbstractCommunicator.send(AbstractCommunicator.java:109)
            at org.mozilla.mozstumbler.communicator.Submitter.cleanSend(Submitter.java:41)
            at org.mozilla.mozstumbler.sync.SyncAdapter.uploadReports(SyncAdapter.java:130)
            at org.mozilla.mozstumbler.sync.SyncAdapter.onPerformSync(SyncAdapter.java:91)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)
03-22 08:20:15.831    3542-3798/org.mozilla.mozstumbler:.ScannerService D/org.mozilla.mozstumbler.communicator.Submitter﹕ Got status: 400
03-22 08:20:15.831    3542-3798/org.mozilla.mozstumbler:.ScannerService D/org.mozilla.mozstumbler.communicator.Submitter﹕ Tried sending: [B@4117e7f8
```

**Comment by tamcap** [comment]
OK. I messed up a bit, but this is a good start. It seems like your MozStumbler is not building the JSON correctly and confuses our server (hence the 400 code).

Would you be so kind and update your MozStumbler to the newest experimental version with tons of debug data being printed? :+1: 

https://github.com/tamcap/MozStumbler/releases/tag/v0.17.1.debug

After you do it, please post the lines that print after 
`[...]org.mozilla.mozstumbler:.ScannerService D/org.mozilla.mozstumbler.communicator.Submitter﹕ Got status: 400`

**Comment by rodmoreno** [comment]
@tamcap with the newest experimental version I get the following error when I see the logs, but nothing of the old 400 error

``````
03-26 08:54:29.533    2154-2448/org.mozilla.mozstumbler:.ScannerService E/org.mozilla.mozstumbler.communicator.Submitter﹕ Error submitting:
    java.io.FileNotFoundException: https://location.services.mozilla.com/v1/submit?key=null
            at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:177)
            at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:270)
            at org.mozilla.mozstumbler.communicator.AbstractCommunicator.sendData(AbstractCommunicator.java:99)
            at org.mozilla.mozstumbler.communicator.AbstractCommunicator.send(AbstractCommunicator.java:119)
            at org.mozilla.mozstumbler.communicator.Submitter.cleanSend(Submitter.java:43)
            at org.mozilla.mozstumbler.sync.SyncAdapter.uploadReports(SyncAdapter.java:130)
            at org.mozilla.mozstumbler.sync.SyncAdapter.onPerformSync(SyncAdapter.java:91)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)```
``````

**Comment by tamcap** [comment]
It seems I messed up again :( Let me figure out what I am doing wrong, and
I will get back to you. Sorry :(

**Comment by rodmoreno** [comment]
@tamcap Don't worry! I almost did not program in Java. From knowing how to program in Java already would have helped.

**Comment by tamcap** [comment]
Boom: https://github.com/tamcap/MozStumbler/releases/tag/v0.17.2.debug This should work.

**Comment by rodmoreno** [comment]
@tamcap With this version I get the following:

```
03-26 09:37:27.556    2997-3208/org.mozilla.mozstumbler:.ScannerService D/org.mozilla.mozstumbler.communicator.Submitter﹕ Tried sending: {"items":[{"wifi":[{"key":"f4c714c9ddaf","signal":-91,"frequency":2427},{"key":"a4b1e99636fc","signal":-88,"frequency":2437},{"key":"58983524bf10","signal":-96,"frequency":2412},{"key":"002568e1fe83","signal":-90,"frequency":2427},{"key":"0cf89329fa50","signal":-98,"frequency":2412},{"key":"001dcef6ac84","signal":-87,"frequency":2452},{"key":"00f5df604094","signal":-88,"frequency":2462},{"key":"001f9f68c362","signal":-90,"frequency":2437},{"key":"0021f0823d12","signal":-95,"frequency":2412},{"key":"002f172e0f3f","signal":-89,"frequency":2437},{"key":"f0feed98e818","signal":-91,"frequency":2412},{"key":"9f2cbed92a42","signal":-91,"frequency":2422},{"key":"002417f017cd","signal":-86,"frequency":2437},{"key":"5c5f1af58ac0","signal":-85,"frequency":2412},{"key":"5c57faf5fa60","signal":-87,"frequency":2462},{"key":"982cbe8daaca","signal":-95,"frequency":2417},{"key":"00f644dee088","signal":-94,"frequency":2412},{"key":"70f23cbd9768","signal":-81,"frequency":2452},{"key":"f4c7f4743694","signal":-81,"frequency":2452},{"key":"5c57faf3ded0","signal":-86,"frequency":2437},{"key":"f4cf14c65344","signal":-90,"frequency":2457},{"key":"08f6ff7cc1c0","signal":-89,"frequency":2412},{"key":"4cf499971360","signal":-49,"frequency":2462}],"lon":-99.09,"time":"2014-03-01","altitude":2290,"cell":[{"asu":18,"radio":"0","mnc":3,"psc":4095,"mcc":334,"cid":59273867,"lac":9512}],"radio":"gsm","accuracy":52,"lat":19.40}]}
03-26 09:37:27.556    2997-3208/org.mozilla.mozstumbler:.ScannerService D/org.mozilla.mozstumbler.communicator.Submitter﹕ Got error message:
```

**Comment by rodmoreno** [comment]
Mor cleaner the JSON:

``` json
{
   "items":[
      {
         "wifi":[
            {
               "key":"f4c714c9ddaf",
               "signal":-91,
               "frequency":2427
            },
            {
               "key":"a4b1e99636fc",
               "signal":-88,
               "frequency":2437
            },
            {
               "key":"58983524bf10",
               "signal":-96,
               "frequency":2412
            },
            {
               "key":"002568e1fe83",
               "signal":-90,
               "frequency":2427
            },
            {
               "key":"0cf89329fa50",
               "signal":-98,
               "frequency":2412
            },
            {
               "key":"001dcef6ac84",
               "signal":-87,
               "frequency":2452
            },
            {
               "key":"00f5df604094",
               "signal":-88,
               "frequency":2462
            },
            {
               "key":"001f9f68c362",
               "signal":-90,
               "frequency":2437
            },
            {
               "key":"0021f0823d12",
               "signal":-95,
               "frequency":2412
            },
            {
               "key":"002f172e0f3f",
               "signal":-89,
               "frequency":2437
            },
            {
               "key":"f0feed98e818",
               "signal":-91,
               "frequency":2412
            },
            {
               "key":"9f2cbed92a42",
               "signal":-91,
               "frequency":2422
            },
            {
               "key":"002417f017cd",
               "signal":-86,
               "frequency":2437
            },
            {
               "key":"5c5f1af58ac0",
               "signal":-85,
               "frequency":2412
            },
            {
               "key":"5c57faf5fa60",
               "signal":-87,
               "frequency":2462
            },
            {
               "key":"982cbe8daaca",
               "signal":-95,
               "frequency":2417
            },
            {
               "key":"00f644dee088",
               "signal":-94,
               "frequency":2412
            },
            {
               "key":"70f23cbd9768",
               "signal":-81,
               "frequency":2452
            },
            {
               "key":"f4c7f4743694",
               "signal":-81,
               "frequency":2452
            },
            {
               "key":"5c57faf3ded0",
               "signal":-86,
               "frequency":2437
            },
            {
               "key":"f4cf14c65344",
               "signal":-90,
               "frequency":2457
            },
            {
               "key":"08f6ff7cc1c0",
               "signal":-89,
               "frequency":2412
            },
            {
               "key":"4cf499971360",
               "signal":-49,
               "frequency":2462
            }
         ],
         "lon":-99.09,
         "time":"2014-03-01",
         "altitude":2290,
         "cell":[
            {
               "asu":18,
               "radio":"0",
               "mnc":3,
               "psc":4095,
               "mcc":334,
               "cid":59273867,
               "lac":9512
            }
         ],
         "radio":"gsm",
         "accuracy":52,
         "lat":19.40
      }
   ]
}
```

**Comment by tamcap** [comment]
Nothing in the error? Interesting.

**Comment by tamcap** [comment]
Anyway:
`"radio":"0",` is the culprit.

**Comment by rodmoreno** [comment]
radio should be something like umts, gsm, lte, cdma or something similar, right?

**Comment by tamcap** [comment]
Yes. It's related to the error you listed in your original post. Trying to wrap my head around it.

**Comment by tamcap** [comment]
I have to punt this one. If the TelephonyManager is unable to give MozStumbler a good response... it just won't work. We might have to make a warning sign at some point for that case.

**Comment by Djfe** [comment]
Maybe the server is able to take a guess for radio from all the other informations that have been sent. 
The server would need to accept radio 0 without errors first though.

**Comment by Djfe** [comment]
mozilla/ichnaea#16

**Comment by illarionov** [comment]
Network type is not known. Looks like ROM bug. 
@rodmoreno, is the network type indicator (blue icon at right-top) is changed ever? What the type of network is shown in system settings -> about -> general information?

I think it would be better to just skip records with unknown network type as invalid data.

**Comment by Djfe** [comment]
@rodmoreno is this still an issue or can @garvankeeley close it?

**Comment by Djfe** [comment]
@cpeterso the troll account ist back :facepalm:

**Comment by Djfe** [comment]
@rodmoreno is this still an issue? the uploader has been rebuild completely and doesn't rely on the sync adapter anymore so this is probably fixed
