### ISSUE TITLE
MozStumbler crashes when adding or removing an account in Android system settings

### ISSUE THREAD

**Issue by cpeterso** [mozilla/MozStumbler#724]
MozStumbler's upload sync adapter throws exceptions when I add or remove an Android account that syncs with my work email and calendar:

```
E/AndroidRuntime(17193): FATAL EXCEPTION: SyncAdapterThread-9
E/AndroidRuntime(17193): java.lang.NullPointerException
E/AndroidRuntime(17193):    at org.mozilla.mozstumbler.service.sync.UploadReports.getMaxId(UploadReports.java:121)
E/AndroidRuntime(17193):    at org.mozilla.mozstumbler.service.sync.UploadReports.uploadReports(UploadReports.java:72)
E/AndroidRuntime(17193):    at org.mozilla.mozstumbler.client.sync.SyncAdapter.onPerformSync(SyncAdapter.java:44)
E/AndroidRuntime(17193):    at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:257)
```

```
W/AccountManagerService( 1057): insertAccountIntoDatabase: Account {name=sync, type=org.mozilla.mozstumbler}, skipping since the account already exists
I/ElegantRequestDirector(15648): I/O exception (javax.net.ssl.SSLException) caught when processing request: Write error: ssl=0x7636d388: I/O error during system call, Broken pipe
I/ElegantRequestDirector(15648): Retrying request
D/org.mozilla.mozstumbler.client.MainApp(11388): Service connected
W/dalvikvm(11388): threadid=12: thread exiting with uncaught exception (group=0x416727c0)
E/AndroidRuntime(11388): FATAL EXCEPTION: SyncAdapterThread-1
E/AndroidRuntime(11388): java.lang.NullPointerException
E/AndroidRuntime(11388):    at org.mozilla.mozstumbler.service.sync.UploadReports.getMaxId(UploadReports.java:121)
E/AndroidRuntime(11388):    at org.mozilla.mozstumbler.service.sync.UploadReports.uploadReports(UploadReports.java:72)
E/AndroidRuntime(11388):    at org.mozilla.mozstumbler.client.sync.SyncAdapter.onPerformSync(SyncAdapter.java:44)
E/AndroidRuntime(11388):    at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:257)
```

```
E/AndroidRuntime(11584): FATAL EXCEPTION: SyncAdapterThread-1
E/AndroidRuntime(11584): java.lang.NullPointerException
E/AndroidRuntime(11584):    at org.mozilla.mozstumbler.service.sync.UploadReports.getMaxId(UploadReports.java:121)
E/AndroidRuntime(11584):    at org.mozilla.mozstumbler.service.sync.UploadReports.uploadReports(UploadReports.java:72)
E/AndroidRuntime(11584):    at org.mozilla.mozstumbler.client.sync.SyncAdapter.onPerformSync(SyncAdapter.java:44)
E/AndroidRuntime(11584):    at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:257)
```

**Comment by garvankeeley** [comment]
As part of Fennec integration work, this code is gone, hopefully landed next week.

**Comment by Djfe** [comment]
@garvankeeley
looks like
#696 
to me
so I guess it has been fixed!?

**Comment by garvankeeley** [comment]
Indeed it has, thanks again @Djfe!

**Comment by Djfe** [comment]
no problem :)
just noticed some issues that got fixed over time/aren't an issue anymore so tried helping to clean up the list
