### ISSUE TITLE
Stumbler crash when clicking the scan button

### ISSUE THREAD

**Issue by almet** [mozilla/MozStumbler#96]
stacktrace:

```
V/LocationManagerService(   93): Location listener died                                                                                     [1189/1617]
V/LocationManagerService(   93): _removeUpdates: listener = Receiver{46303ee0 Listener android.os.BinderPr
oxy@46499a60}
D/WifiService(   93): releaseWifiLockLocked: WifiLock{MozStumbler type=2 binder=android.os.BinderProxy@465
25160}
D/WifiService(   93): enable and start wifi due to updateWifiState
E/AndroidRuntime(  964): FATAL EXCEPTION: main
E/AndroidRuntime(  964): java.lang.IllegalStateException: Could not execute method of the activity
E/AndroidRuntime(  964):        at android.view.View$1.onClick(View.java:2072)
E/AndroidRuntime(  964):        at android.view.View.performClick(View.java:2408)
E/AndroidRuntime(  964):        at android.view.View$PerformClick.run(View.java:8817)
E/AndroidRuntime(  964):        at android.os.Handler.handleCallback(Handler.java:587)
E/AndroidRuntime(  964):        at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(  964):        at android.os.Looper.loop(Looper.java:144)
E/AndroidRuntime(  964):        at android.app.ActivityThread.main(ActivityThread.java:4937)
E/AndroidRuntime(  964):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  964):        at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime(  964):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.j
ava:868)
E/AndroidRuntime(  964):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
E/AndroidRuntime(  964):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(  964): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(  964):        at org.mozilla.mozstumbler.MainActivity.onClick_ToggleScanning(MainActivit
y.java:204)
E/AndroidRuntime(  964):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  964):        at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime(  964):        at android.view.View$1.onClick(View.java:2067)
E/AndroidRuntime(  964):        ... 11 more
E/AndroidRuntime(  964): Caused by: java.lang.NullPointerException
E/AndroidRuntime(  964):        ... 15 more
W/ActivityManager(   93):   Force finishing activity org.mozilla.mozstumbler/.MainActivity
W/ActivityManager(   93): Activity pause timeout for HistoryRecord{46221930 org.mozilla.mozstumbler/.MainA
ctivity}
I/WindowManager(   93): WIN DEATH: Window{4644e6e0 org.mozilla.mozstumbler/org.mozilla.mozstumbler.MainAct
ivity paused=false}
I/ActivityManager(   93): Process org.mozilla.mozstumbler (pid 964) has died.
I/WindowManager(   93): WIN DEATH: Window{46322fa0 org.mozilla.mozstumbler/org.mozilla.mozstumbler.MainAct
ivity paused=false}
I/UsageStats(   93): Unexpected resume of com.htc.launcher while already resumed in org.mozilla.mozstumble
```

**Comment by cpeterso** [comment]
I believe the stumbler activity crashed when trying to talk to the stumbler service after the service crashed from bug #97.
