### ISSUE TITLE
ANR with v0.40.0

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/MozStumbler#962]
Cmd line: org.mozilla.mozstumbler

JNI: CheckJNI is off; workarounds are off; pins=0; globals=489

DALVIK THREADS:
(mutexes: tll=0 tsl=0 tscl=0 ghl=0)

"main" prio=5 tid=1 SUSPENDED
  | group="main" sCount=1 dsCount=0 obj=0x415efca8 self=0x41529408
  | sysTid=29611 nice=0 sched=0/0 cgrp=apps handle=1074540884
  | state=S schedstat=( 205367914473 139158490621 722600 ) utm=18315 stm=2221 core=2
  at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:~138)
  at java.lang.StringBuilder.append(StringBuilder.java:216)
  at org.json.JSONStringer.string(JSONStringer.java:303)
  at org.json.JSONStringer.key(JSONStringer.java:375)
  at org.json.JSONObject.writeTo(JSONObject.java:672)
  at org.json.JSONStringer.value(JSONStringer.java:237)
  at org.json.JSONArray.writeTo(JSONArray.java:602)
  at org.json.JSONStringer.value(JSONStringer.java:233)
  at org.json.JSONObject.writeTo(JSONObject.java:672)
  at org.json.JSONObject.toString(JSONObject.java:641)
  at org.mozilla.mozstumbler.service.stumblerthread.Reporter.flush(Reporter.java:256)
  at org.mozilla.mozstumbler.service.stumblerthread.Reporter.onReceive(Reporter.java:188)
  at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
  at android.support.v4.content.LocalBroadcastManager.sendBroadcastSync(LocalBroadcastManager.java:278)
  at org.mozilla.mozstumbler.service.stumblerthread.scanners.GPSScanner$1.onNmeaReceived(GPSScanner.java:94)
  at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1461)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5001)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
  at dalvik.system.NativeStart.main(Native Method)

full log at https://gist.github.com/kbrosnan/64691de6a2106e4d05a1

**Comment by garvankeeley** [comment]
It hung writing the JSON object for the current scan to the GUI log, which is surprising :). 
Any idea if you had a really high number of wifis? Was this on your nexus 5? 
Did it recover? 
How did you get this log, from power button debug logging?

**Comment by kbrosnan** [comment]
I got the ANR dialog and chose close app option so it did not recover. It is on my Nexus 5, though I was just stumbling during lunch ~60 min (2km). I got the log from adb pull /data/anr/traces.txt

**Comment by kbrosnan** [comment]
Hit this on a Galaxy S5 as well. https://gist.github.com/kbrosnan/f3cb7cc7fcb4d0044bf9

**Comment by garvankeeley** [comment]
Marking fixed by #993
