### ISSUE TITLE
When switching OSMDroid tile providers, we get receiver leakage

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/MozStumbler#963]
E/ActivityThread(  802): Activity org.mozilla.mozstumbler.client.navdrawer.MainDrawerActivity has leaked IntentReceiver org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase$MyBroadcastReceiver@407439d8 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(  802): android.app.IntentReceiverLeaked: Activity org.mozilla.mozstumbler.client.navdrawer.MainDrawerActivity has leaked IntentReceiver org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase$MyBroadcastReceiver@407439d8 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(  802):    at org.mozilla.mozstumbler.client.mapview.tiles.AbstractMapOverlay.<init>(AbstractMapOverlay.java:39)
E/ActivityThread(  802):    at org.mozilla.mozstumbler.client.mapview.tiles.CoverageOverlay.<init>(CoverageOverlay.java:20)
E/ActivityThread(  802):    at org.mozilla.mozstumbler.client.mapview.MapActivity.mapNetworkConnectionChanged(MapActivity.java:335)
E/ActivityThread(  802):    at org.mozilla.mozstumbler.client.mapview.MapActivity.access$900(MapActivity.java:62)
E/ActivityThread(  802):    at org.mozilla.mozstumbler.client.mapview.MapActivity$5.onReceive(MapActivity.java:341)

**Comment by garvankeeley** [comment]
From log in Issue #869
