### ISSUE TITLE
Stumbler crash because android.telephony.gsm.GsmCellLocation.getPsc doesn't exist

### ISSUE THREAD

**Issue by almet** [mozilla/MozStumbler#97]
stack trace (from adb logcat):

```
E/AndroidRuntime(  973): FATAL EXCEPTION: Thread-9
E/AndroidRuntime(  973): java.lang.NoSuchMethodError: android.telephony.gsm.GsmCellLocation.getPsc
E/AndroidRuntime(  973):        at org.mozilla.mozstumbler.Scanner.getCellInfo(Scanner.java:264)
E/AndroidRuntime(  973):        at org.mozilla.mozstumbler.Scanner.onLocationChanged(Scanner.java:227)
E/AndroidRuntime(  973):        at android.location.LocationManager$ListenerTransport._handleMessage(Locat
ionManager.java:191)
E/AndroidRuntime(  973):        at android.location.LocationManager$ListenerTransport.access$000(LocationM
anager.java:124)
E/AndroidRuntime(  973):        at android.location.LocationManager$ListenerTransport$1.handleMessage(Loca
tionManager.java:140)
E/AndroidRuntime(  973):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(  973):        at android.os.Looper.loop(Looper.java:144)
E/AndroidRuntime(  973):        at org.mozilla.mozstumbler.ScannerService$LooperThread.run(ScannerService.
java:110)

```

**Comment by cpeterso** [comment]
We are calling `GsmCellLocation.getPsc()` which was added in Gingerbread. We need a version check for Froyo. All the other `GsmCellLocation` methods are supported by Froyo; we just want to skip `getPsc()`.

https://developer.android.com/reference/android/telephony/gsm/GsmCellLocation.html#getPsc%28%29

btw, Fennec has the same bug on Froyo: https://bugzil.la/912748
