### ISSUE TITLE
OutOfMemoryError finalizing reports

### ISSUE THREAD

**Issue by crankycoder** [mozilla/MozStumbler#993]
Crash while generating JSON:

```
org.mozilla.mozstumbler.service.stumblerthread.datahandling.DataStorageManager.finalizeReports(DataStorageManager.java:417)
```

https://github.com/mozilla/MozStumbler/blob/v0.40.1.0/android/src/main/java/org/mozilla/mozstumbler/service/stumblerthread/datahandling/DataStorageManager.java#L417

```
java.lang.OutOfMemoryError
at java.lang.String.<init>(String.java:422)
at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:642)
at java.lang.StringBuilder.toString(StringBuilder.java:663)
at org.mozilla.mozstumbler.service.stumblerthread.datahandling.DataStorageManager.finalizeReports(DataStorageManager.java:417)
at org.mozilla.mozstumbler.service.stumblerthread.datahandling.DataStorageManager.saveCurrentReportsToDisk(DataStorageManager.java:429)
at org.mozilla.mozstumbler.service.stumblerthread.datahandling.DataStorageManager.insert(DataStorageManager.java:448)
at org.mozilla.mozstumbler.service.stumblerthread.Reporter.flush(Reporter.java:259)
at org.mozilla.mozstumbler.service.stumblerthread.Reporter.onReceive(Reporter.java:188)
at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
at android.support.v4.content.LocalBroadcastManager.sendBroadcastSync(LocalBroadcastManager.java:278)
at org.mozilla.mozstumbler.service.stumblerthread.scanners.GPSScanner$1.onNmeaReceived(GPSScanner.java:94)
at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1432)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:152)
at android.app.ActivityThread.main(ActivityThread.java:5136)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:744)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by crankycoder** [comment]
More details - this happens on a 512MB Android 4.3 device: http://www.gsmarena.com/t_mobile_concord-4949.php

**Comment by garvankeeley** [comment]
Related to https://github.com/mozilla/MozStumbler/issues/962

**Comment by garvankeeley** [comment]
This is the first bug we have that would impact Fennec collection. And it is a crasher.
